---
config:
  look: classic
---
sequenceDiagram
    participant P as PatrolNode
    participant Ph as PhotoCapturer
    participant R as LLMReporterNode
    participant V as PerceptionNode
    participant O@{ "type": "entity" } as Ollama API
    participant Disco@{ "type": "database" } as Disco Local

    P->>Disco: clean_all_orphan_folders() (Borra basura previa)

    P->>Disco: get_next_available_folder() (Crea ej. vuelta_A)
    P->>Ph: Service SetParameters (current_save_dir = vuelta_A)

    rect rgb(240, 248, 255)
        loop Cada punto de ruta (Vuelta A)
            P->>P: Navega hacia Waypoint
            opt Usuario pulsa 'd'
                P->>R: cancel_goal_async() (Aborta meta anterior)
            end
            opt Usuario pulsa 's'
                P->>P: cancelTask() (Salta Waypoint actual)
            end
            Ph->>Ph: Escucha /odom y /head_front_camera
            alt Si avanzó y MSE > umbral
                Ph->>Disco: Guarda foto y metadata.csv en vuelta_A
            end
        end
    end

    loop Bucle Infinito (Pipeline Concurrente)
        P-)R: Envía Meta Asíncrona (Analizar vuelta anterior)

        par Proceso A: Robot ejecuta siguiente vuelta en físico
            rect rgb(240, 255, 240)
                P->>Disco: get_next_available_folder() (Crea ej. vuelta_B, C...)
                P->>Ph: Service SetParameters (Nueva carpeta)
                loop Cada punto de ruta (Nueva iteración/vuelta)
                    P->>P: Navegación y captura de fotos
                    Ph->>Disco: Guarda datos de la nueva vuelta
                end
            end
        and Proceso B: IA analiza vuelta anterior en 2º Plano
            rect rgb(255, 245, 238)
                R->>Disco: Lee datos de la vuelta finalizada
                loop Por cada zona
                    R->>V: Llama /analyze_image(path)
                    V->>O: Inferencia (VLM / YOLO)
                    O-->>V: JSON {descripción, alerta}
                    V-->>R: Devuelve actividades
                    R-->>P: Publish Feedback (% completado, Zona actual)
                end
                R->>O: Envía Mini-Reportes globales al LLM
                O-->>R: Genera Resumen Global
                R-->>P: Devuelve Result (Éxito y Reporte Final)
                P->>Disco: delete_folder(Vuelta finalizada)
            end
        end
    end
