# Request (meta que envía el nodo patrulla)
string folder_path
---
# Result (respuesta del reportero al finalizar)
bool success
string final_report
---
# Feedback 
string current_zone
float32 percentage_complete