---
config:
  look: classic
---
sequenceDiagram
    participant P as PatrolNode
    participant Ph as PhotosNode
    participant R as LLMReporterNode
    participant V as PerceptionNode (Activo)
    participant O@{ "type": "entity" } as Ollama API
    participant Disco@{ "type": "database" }

    P->>P: Inicia vuelta (Bucle de Waypoints)
    par Navegación y Captura
        loop Cada punto de ruta
            P->>P: Navega hacia Waypoint
            Ph->>Ph: Escucha /odom y /head_front_camera
            alt Si avanzó la distancia objetivo
                Ph->>Ph: Compara MSE de imagen
                Ph->>Disco: Guarda foto y metadata.csv
            end
        end
    end

    P->>R: Llama servicio /generate_patrol_report
    Disco->>R: Lee metadata.csv y agrupa por Zonas
    
    loop Por cada zona
        alt Imagen Individual
            loop Por cada imagen
                R->>V: Llama servicio /analyze_image(path)
                alt VLM
                    V->>O: Pide descripción visual
                    O-->>V: JSON con {descripción, alerta}
                else YOLO
                    V->>V: Inferencia local (Postura/Caídas)
                else Híbrido
                    V->>O: (VLM) Pide descripción visual
                    O-->>V: (VLM) JSON con {descripción, alerta}
                    V->>V: (YOLO) Inferencia local (Postura/Caídas)

                end
                V-->>R: Devuelve JSON de incidencias
            end
        else Secuencia
            R->>V: Llama servicio /analyze_image(path)

            V->>O: Pide descripción visual
            O-->>V: JSON con {descripción, alerta}

            V->>V: Inferencia local (Postura/Caídas)

            V-->>R: Devuelve JSON de incidencias
        end
    end
    R->>O: Envía Mini-Reportes globales al LLM (Llama3)
    O-->>R: Genera Resumen Ejecutivo de Seguridad
    R-->>P: Devuelve success y el Reporte de la vuelta
    P->>R: Llama servicio /clean_patrol_data
    R->>Disco: Borra fotos y metadata.csv
    P->>P: Inicia siguiente vuelta